--[[
    --[[
   If you want the project to work correctly, you need to create your own animations
   for the rbxassetid's in the src/replicated/Modules/AnimData.luau file
   (if the animations are not visible)
  
   Other than that, this project will not receive any more updates because
   I could not find the necessary animations, sounds and effects for the project.
   
   @date: DD/MM/YY 26.05.2026 21.45
]]